version: "3"

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq_m_order
        restart: always
        ports:
            - 5672:5672
            - ${RMQ_PORT_CLI}:${RMQ_PORT_CLI}
        volumes:
            - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/

        environment:
            - RABBITMQ_DEFAULT_USER=${RQM_USER}
            - RABBITMQ_DEFAULT_PASS=${RQM_PASS}
