version: "3"

services:
    db:
        container_name: postgress_order
        image: postgres:15.2
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - ./db_backup:/var/lib/postgresql/data/
        expose:
            - ${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq_m_order
        restart: always
        ports:
            - 5672:5672
            - ${RMQ_PORT_CLI}:${RMQ_PORT_CLI}
        volumes:
            - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/

        environment:
            - RABBITMQ_DEFAULT_USER=${RQM_USER}
            - RABBITMQ_DEFAULT_PASS=${RQM_PASS}
