version: "3"

services:
<<<<<<< HEAD:Order/database/docker-compose.yml
    db:
        container_name: postgress_order
        image: postgres:15.2
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - ./db_backup:/var/lib/postgresql/data/
        expose:
            - ${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
=======
  db:
    container_name: postgress_order
    image: postgres:15.2
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db_backup:/var/lib/postgresql/data/
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
>>>>>>> a65b844d36be53b1777984772a2a5aa4a97b7cee:Order/dataModel/docker-compose.yml
